# Generated by Django 4.2.24 on 2025-10-13 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('class_time', models.TimeField(verbose_name='Class Time')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duration (Minutes)')),
                ('total_sessions', models.PositiveIntegerField(verbose_name='Total Sessions')),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Full Price')),
                ('installment_3_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='3 Installments Price')),
                ('installment_6_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='6 Installments Price')),
                ('max_students', models.PositiveIntegerField(verbose_name='Maximum Students')),
                ('current_enrollments', models.PositiveIntegerField(default=0, verbose_name='Current Enrollments')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_cohorts', to=settings.AUTH_USER_MODEL, verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Cohort',
                'verbose_name_plural': 'Cohorts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CohortEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('suspended', 'Suspended')], default='pending', max_length=20, verbose_name='Status')),
                ('payment_type', models.CharField(choices=[('full', 'Full Payment'), ('installment_3', '3 Installments'), ('installment_6', '6 Installments')], max_length=20, verbose_name='Payment Type')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Paid')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Remaining Amount')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled At')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cohorts.cohort', verbose_name='Cohort')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Cohort Enrollment',
                'verbose_name_plural': 'Cohort Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'cohort')},
            },
        ),
        migrations.CreateModel(
            name='CohortSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField(verbose_name='Session Number')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('scheduled_date', models.DateField(verbose_name='Scheduled Date')),
                ('scheduled_time', models.TimeField(verbose_name='Scheduled Time')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duration (Minutes)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Actual Start Time')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Actual End Time')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Session Notes')),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='cohorts/recordings/', verbose_name='Recording File')),
                ('recording_url', models.URLField(blank=True, null=True, verbose_name='Recording URL')),
                ('is_recording_available', models.BooleanField(default=False, verbose_name='Is Recording Available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cohorts.cohort', verbose_name='Cohort')),
            ],
            options={
                'verbose_name': 'Cohort Session',
                'verbose_name_plural': 'Cohort Sessions',
                'ordering': ['session_number'],
                'unique_together': {('cohort', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='CohortInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='Installment Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('due', 'Due'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='cohorts.cohortenrollment', verbose_name='Enrollment')),
            ],
            options={
                'verbose_name': 'Cohort Installment',
                'verbose_name_plural': 'Cohort Installments',
                'ordering': ['installment_number'],
                'unique_together': {('enrollment', 'installment_number')},
            },
        ),
        migrations.CreateModel(
            name='CohortAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False, verbose_name='Is Present')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='Arrived At')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Left At')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='cohorts.cohortenrollment', verbose_name='Enrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='cohorts.cohortsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Cohort Attendance',
                'verbose_name_plural': 'Cohort Attendance',
                'unique_together': {('enrollment', 'session')},
            },
        ),
    ]
