# Generated by Django 4.2.24 on 2025-10-02 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app.therapy_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('individual', 'Individual Therapy'), ('couple', 'Couple Therapy'), ('family', 'Family Therapy'), ('group', 'Group Therapy'), ('child', 'Child Therapy'), ('adolescent', 'Adolescent Therapy'), ('addiction', 'Addiction Therapy'), ('trauma', 'Trauma Therapy'), ('anxiety', 'Anxiety Therapy'), ('depression', 'Depression Therapy'), ('other', 'Other')], max_length=50, verbose_name='Specialization')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('education', models.TextField(blank=True, null=True, verbose_name='Education')),
                ('certifications', models.TextField(blank=True, null=True, verbose_name='Certifications')),
                ('experience_start_date', models.DateField(blank=True, null=True, verbose_name='Experience Start Date')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hourly Rate')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='therapist_profiles/', verbose_name='Profile Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Therapist',
                'verbose_name_plural': 'Therapists',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='SessionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Status')),
                ('mode', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person'), ('phone', 'Phone Call')], max_length=20, verbose_name='Mode')),
                ('preferred_date', models.DateField(verbose_name='Preferred Date')),
                ('preferred_time', models.TimeField(verbose_name='Preferred Time')),
                ('alternative_dates', models.JSONField(default=list, verbose_name='Alternative Dates')),
                ('goals', models.TextField(blank=True, null=True, verbose_name='Session Goals')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('confirmed_date', models.DateField(blank=True, null=True, verbose_name='Confirmed Date')),
                ('confirmed_time', models.TimeField(blank=True, null=True, verbose_name='Confirmed Time')),
                ('confirmation_notes', models.TextField(blank=True, null=True, verbose_name='Confirmation Notes')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('croom_class_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Croom Class ID')),
                ('croom_class_url', models.URLField(blank=True, null=True, verbose_name='Croom Class URL')),
                ('croom_meeting_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Croom Meeting ID')),
                ('croom_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Croom Password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed By')),
                ('session_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='therapy_sessions.sessiontype', verbose_name='Session Type')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='therapy_sessions.therapist', verbose_name='Therapist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_bookings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Session Booking',
                'verbose_name_plural': 'Session Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='session',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_sessions', to='therapy_sessions.therapist', verbose_name='Therapist'),
        ),
        migrations.AlterField(
            model_name='therapistavailability',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='therapy_sessions.therapist', verbose_name='Therapist'),
        ),
    ]
