# Generated by Django 4.2.24 on 2024-12-19 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کلینیک')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='ظرفیت')),
                ('facilities', models.JSONField(default=dict, verbose_name='امکانات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'محل کلینیک',
                'verbose_name_plural': 'محل\u200cهای کلینیک',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع نوبت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('default_duration_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)], verbose_name='مدت زمان پیش\u200cفرض (دقیقه)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='رنگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'نوع نوبت',
                'verbose_name_plural': 'انواع نوبت',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سیاست')),
                ('hours_before_appointment', models.PositiveIntegerField(help_text='حداقل ساعت قبل از نوبت که این سیاست اعمال می\u200cشود', verbose_name='ساعت قبل از نوبت')),
                ('cancellation_fee_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد هزینه لغو')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'سیاست لغو',
                'verbose_name_plural': 'سیاست\u200cهای لغو',
                'ordering': ['-hours_before_appointment'],
            },
        ),
        migrations.CreateModel(
            name='TherapistSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.cliniclocation', verbose_name='محل کار')),
                ('therapist', models.ForeignKey(limit_choices_to={'user_type': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='درمانگر')),
            ],
            options={
                'verbose_name': 'برنامه درمانگر',
                'verbose_name_plural': 'برنامه\u200cهای درمانگران',
                'ordering': ['therapist', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TherapistTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('reason', models.CharField(max_length=200, verbose_name='دلیل')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('therapist', models.ForeignKey(limit_choices_to={'user_type': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to=settings.AUTH_USER_MODEL, verbose_name='درمانگر')),
            ],
            options={
                'verbose_name': 'مرخصی درمانگر',
                'verbose_name_plural': 'مرخصی\u200cهای درمانگران',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField(verbose_name='زمان نوبت')),
                ('duration_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)], verbose_name='مدت زمان (دقیقه)')),
                ('status', models.CharField(choices=[('scheduled', 'رزرو شده'), ('confirmed', 'تأیید شده'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('no_show', 'عدم حضور'), ('rescheduled', 'تغییر زمان')], default='scheduled', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('appointment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointmenttype', verbose_name='نوع نوبت')),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL, verbose_name='مراجع')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.cliniclocation', verbose_name='محل نوبت')),
                ('therapist', models.ForeignKey(limit_choices_to={'user_type': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_appointments', to=settings.AUTH_USER_MODEL, verbose_name='درمانگر')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['-scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ لغو')),
                ('reason', models.TextField(verbose_name='دلیل لغو')),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه لغو')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ بازگشت')),
                ('policy_applied', models.CharField(blank=True, max_length=100, null=True, verbose_name='سیاست اعمال شده')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='appointments.appointment', verbose_name='نوبت')),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='لغو شده توسط')),
            ],
            options={
                'verbose_name': 'لغو نوبت',
                'verbose_name_plural': 'لغوهای نوبت',
                'ordering': ['-cancelled_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('email', 'ایمیل'), ('sms', 'پیامک'), ('push', 'اعلان')], max_length=10, verbose_name='نوع یادآوری')),
                ('scheduled_time', models.DateTimeField(verbose_name='زمان ارسال')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال واقعی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('sent', 'ارسال شده'), ('failed', 'ناموفق')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment', verbose_name='نوبت')),
            ],
            options={
                'verbose_name': 'یادآوری نوبت',
                'verbose_name_plural': 'یادآوری\u200cهای نوبت',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentReschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rescheduled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تغییر زمان')),
                ('reason', models.TextField(verbose_name='دلیل تغییر زمان')),
                ('reschedule_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه تغییر زمان')),
                ('new_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescheduled_from', to='appointments.appointment', verbose_name='نوبت جدید')),
                ('original_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='appointments.appointment', verbose_name='نوبت اصلی')),
                ('rescheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تغییر زمان توسط')),
            ],
            options={
                'verbose_name': 'تغییر زمان نوبت',
                'verbose_name_plural': 'تغییر زمان\u200cهای نوبت',
                'ordering': ['-rescheduled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['therapist', 'scheduled_datetime'], name='appointments_therapist_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', 'scheduled_datetime'], name='appointments_client_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointments_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='therapistschedule',
            unique_together={('therapist', 'day_of_week', 'start_time')},
        ),
    ]
