# Generated by Django 4.2.24 on 2025-10-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_therapi_d3af8e_idx',
            old_name='appointments_therapist_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_client__47286d_idx',
            old_name='appointments_client_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_status_8fe9d7_idx',
            old_name='appointments_status_idx',
        ),
    ]
