# Generated by Django 4.2.24 on 2025-10-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_appointments_therapist_idx_appointment_therapi_d3af8e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttype',
            name='specializations',
            field=models.JSONField(default=list, help_text='لیست تخصص\u200cهایی که این نوع نوبت برای آن\u200cها مناسب است', verbose_name='تخصص\u200cهای مرتبط'),
        ),
    ]
