# Generated by Django 4.2.24 on 2025-11-12 14:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_orderitem_item_type'),
        ('appointments', '0003_appointmenttype_specializations'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='مبلغ ودیعه'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_deposit', to='payment.order', verbose_name='سفارش ودیعه'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_paid',
            field=models.BooleanField(default=False, verbose_name='ودیعه پرداخت شده است؟'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت ودیعه'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_deposit', to='payment.payment', verbose_name='پرداخت ودیعه'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_required',
            field=models.BooleanField(default=False, verbose_name='نیاز به ودیعه'),
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='در صورت نیاز به ودیعه، مبلغ آن را وارد کنید', max_digits=10, verbose_name='مبلغ ودیعه'),
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='requires_deposit',
            field=models.BooleanField(default=False, verbose_name='نیاز به ودیعه'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending_deposit', 'در انتظار ودیعه'), ('scheduled', 'رزرو شده'), ('confirmed', 'تأیید شده'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('no_show', 'عدم حضور'), ('rescheduled', 'تغییر زمان')], default='scheduled', max_length=20, verbose_name='وضعیت'),
        ),
    ]
