# Generated by Django 4.2.24 on 2025-11-12 14:47

from decimal import Decimal
from django.db import migrations, models


def set_default_deposit_amount(apps, schema_editor):
    AppointmentType = apps.get_model('appointments', 'AppointmentType')
    Appointment = apps.get_model('appointments', 'Appointment')

    AppointmentType.objects.all().update(
        deposit_amount=Decimal('100000.00'),
        requires_deposit=True
    )

    Appointment.objects.filter(deposit_required=True).update(
        deposit_amount=Decimal('100000.00')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_deposit_amount_appointment_deposit_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=10, verbose_name='مبلغ ودیعه'),
        ),
        migrations.AlterField(
            model_name='appointmenttype',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000.00'), help_text='در صورت نیاز به ودیعه، مبلغ آن را وارد کنید', max_digits=10, verbose_name='مبلغ ودیعه'),
        ),
        migrations.AlterField(
            model_name='appointmenttype',
            name='requires_deposit',
            field=models.BooleanField(default=True, verbose_name='نیاز به ودیعه'),
        ),
        migrations.RunPython(set_default_deposit_amount, migrations.RunPython.noop),
    ]
