# Generated by Django 4.2.24 on 2025-10-20 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminbackup',
            options={'ordering': ['-created_at'], 'verbose_name': 'پشتیبان ادمین', 'verbose_name_plural': 'پشتیبان های ادمین'},
        ),
        migrations.AlterModelOptions(
            name='admindashboard',
            options={'verbose_name': 'داشبورد ادمین', 'verbose_name_plural': 'داشبوردهای ادمین'},
        ),
        migrations.AlterModelOptions(
            name='adminlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'لاگ ادمین', 'verbose_name_plural': 'لاگ های ادمین'},
        ),
        migrations.AlterModelOptions(
            name='adminnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'اعلان ادمین', 'verbose_name_plural': 'اعلان های ادمین'},
        ),
        migrations.AlterModelOptions(
            name='adminsetting',
            options={'ordering': ['setting_type', 'key'], 'verbose_name': 'تنظیمات ادمین', 'verbose_name_plural': 'تنظیمات ادمین'},
        ),
        migrations.AlterModelOptions(
            name='adminwidget',
            options={'ordering': ['position'], 'verbose_name': 'ادمین ویجت', 'verbose_name_plural': 'ادمین ویجت ها'},
        ),
        migrations.AlterField(
            model_name='adminbackup',
            name='backup_type',
            field=models.CharField(choices=[('full', 'Full Backup'), ('incremental', 'Incremental Backup'), ('differential', 'Differential Backup')], default='full', max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='adminbackup',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تکمیل شده در'),
        ),
        migrations.AlterField(
            model_name='adminbackup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='adminbackup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_backups', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
        migrations.AlterField(
            model_name='adminbackup',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='پیام خطا'),
        ),
        migrations.AlterField(
            model_name='adminbackup',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='مسیر فایل'),
        ),
        migrations.AlterField(
            model_name='adminbackup',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='اندازه فایل'),
        ),
        migrations.AlterField(
            model_name='adminbackup',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='adminbackup',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شروع شده در'),
        ),
        migrations.AlterField(
            model_name='adminbackup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='admindashboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='admindashboard',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='admindashboard',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='admindashboard',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='admindashboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('import', 'Import'), ('backup', 'Backup'), ('restore', 'Restore')], max_length=20, verbose_name='عمل'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مدل'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه شیء'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='مرورگر کاربر'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='عمومی'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خواندن'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='admin_notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربران هدف'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='is_encrypted',
            field=models.BooleanField(default=False, verbose_name='رمزگذاری شده'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='key',
            field=models.CharField(max_length=100, unique=True, verbose_name='کلید'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='setting_type',
            field=models.CharField(choices=[('general', 'General'), ('security', 'Security'), ('email', 'Email'), ('payment', 'Payment'), ('notification', 'Notification'), ('backup', 'Backup')], default='general', max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='value',
            field=models.TextField(verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='adminwidget',
            name='config',
            field=models.JSONField(default=dict, verbose_name='پیکربندی'),
        ),
        migrations.AlterField(
            model_name='adminwidget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='adminwidget',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='admin_panel.admindashboard', verbose_name='داشبورد'),
        ),
        migrations.AlterField(
            model_name='adminwidget',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='adminwidget',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='adminwidget',
            name='size',
            field=models.CharField(default='medium', max_length=20, verbose_name='اندازه'),
        ),
        migrations.AlterField(
            model_name='adminwidget',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='adminwidget',
            name='widget_type',
            field=models.CharField(choices=[('stat', 'Statistics'), ('chart', 'Chart'), ('table', 'Table'), ('list', 'List'), ('custom', 'Custom')], max_length=20, verbose_name='نوع ویجت'),
        ),
    ]
