# Generated by Django 4.2.24 on 2025-10-20 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0002_add_slug_to_testcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'پاسخ', 'verbose_name_plural': 'پاسخ\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order'], 'verbose_name': 'گزینه', 'verbose_name_plural': 'گزینه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='psychologicaltest',
            options={'ordering': ['-created_at'], 'verbose_name': 'تست روانشناسی', 'verbose_name_plural': 'تست\u200cهای روانشناسی'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AlterModelOptions(
            name='testcategory',
            options={'ordering': ['name'], 'verbose_name': 'دسته\u200cبندی تست', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای تست'},
        ),
        migrations.AlterModelOptions(
            name='testpurchase',
            options={'ordering': ['-purchased_at'], 'verbose_name': 'خرید تست', 'verbose_name_plural': 'خریدهای تست'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'نتیجه تست', 'verbose_name_plural': 'نتایج تست'},
        ),
        migrations.AlterModelOptions(
            name='testsession',
            options={'ordering': ['-started_at'], 'verbose_name': 'جلسه تست', 'verbose_name_plural': 'جلسات تست'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پاسخ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='number_answer',
            field=models.FloatField(blank=True, null=True, verbose_name='پاسخ عددی'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.question', verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, related_name='answers', to='tests.choice', verbose_name='گزینه\u200cهای انتخاب شده'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.testsession', verbose_name='جلسه'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_answer',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ متنی'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='متن گزینه'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='order',
            field=models.PositiveIntegerField(verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='tests.question', verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='score',
            field=models.IntegerField(default=0, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='value',
            field=models.CharField(max_length=50, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='psychologicaltest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.testcategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='psychologicaltest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='psychologicaltest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tests', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
        migrations.AlterField(
            model_name='psychologicaltest',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='psychologicaltest',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, verbose_name='سطح دشواری'),
        ),
        migrations.AlterField(
            model_name='psychologicaltest',
            name='estimated_duration',
            field=models.PositiveIntegerField(help_text='مدت (دقیقه)', verbose_name='مدت تخمینی'),
        ),
        migrations.AlterField(
            model_name='psychologicaltest',
            name='instructions',
            field=models.TextField(verbose_name='دستورالعمل\u200cها'),
        ),
        migrations.AlterField(
            model_name='psychologicaltest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='psychologicaltest',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='رایگان'),
        ),
        migrations.AlterField(
            model_name='psychologicaltest',
            name='max_age',
            field=models.PositiveIntegerField(default=100, verbose_name='حداکثر سن'),
        ),
        migrations.AlterField(
            model_name='psychologicaltest',
            name='min_age',
            field=models.PositiveIntegerField(default=0, verbose_name='حداقل سن'),
        ),
        migrations.AlterField(
            model_name='psychologicaltest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='psychologicaltest',
            name='requires_therapist',
            field=models.BooleanField(default=False, verbose_name='نیاز به درمانگر'),
        ),
        migrations.AlterField(
            model_name='psychologicaltest',
            name='test_type',
            field=models.CharField(choices=[('personality', 'Personality'), ('cognitive', 'Cognitive'), ('emotional', 'Emotional'), ('behavioral', 'Behavioral'), ('clinical', 'Clinical')], max_length=20, verbose_name='نوع تست'),
        ),
        migrations.AlterField(
            model_name='psychologicaltest',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='psychologicaltest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='اجباری'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='متن سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('likert_scale', 'Likert Scale'), ('text', 'Text Input'), ('number', 'Number Input')], max_length=20, verbose_name='نوع سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.psychologicaltest', verbose_name='تست'),
        ),
        migrations.AlterField(
            model_name='testcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='testcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='testpurchase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='testpurchase',
            name='payment_method',
            field=models.CharField(max_length=50, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='testpurchase',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید'),
        ),
        migrations.AlterField(
            model_name='testpurchase',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='tests.psychologicaltest', verbose_name='تست'),
        ),
        migrations.AlterField(
            model_name='testpurchase',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تراکنش'),
        ),
        migrations.AlterField(
            model_name='testpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_purchases', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تولید'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='interpretation',
            field=models.TextField(verbose_name='تفسیر'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='max_score',
            field=models.FloatField(verbose_name='حداکثر امتیاز'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='percentage',
            field=models.FloatField(verbose_name='درصد'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='توصیه\u200cها'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='tests.testsession', verbose_name='جلسه'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='total_score',
            field=models.FloatField(verbose_name='امتیاز کل'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تکمیل شده در'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.question', verbose_name='سوال فعلی'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='شروع شده در'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tests.psychologicaltest', verbose_name='تست'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
