# Generated by Django 4.2.24 on 2025-09-17 13:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.CharField(max_length=300, verbose_name='Short Description')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, verbose_name='Difficulty')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount Price')),
                ('is_free', models.BooleanField(default=False, verbose_name='Is Free')),
                ('duration_hours', models.PositiveIntegerField(verbose_name='Duration (Hours)')),
                ('language', models.CharField(default='fa', max_length=10, verbose_name='Language')),
                ('level', models.CharField(max_length=50, verbose_name='Level')),
                ('prerequisites', models.TextField(blank=True, null=True, verbose_name='Prerequisites')),
                ('learning_objectives', models.TextField(verbose_name='Learning Objectives')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='Thumbnail')),
                ('video_intro', models.FileField(blank=True, null=True, upload_to='courses/videos/', verbose_name='Intro Video')),
                ('enrollment_count', models.PositiveIntegerField(default=0, verbose_name='Enrollment Count')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Review Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, null=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('is_required', models.BooleanField(default=True, verbose_name='Is Required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Module',
                'verbose_name_plural': 'Course Modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoursePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Purchased At')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Payment Method')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID')),
            ],
            options={
                'verbose_name': 'Course Purchase',
                'verbose_name_plural': 'Course Purchases',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('title', models.CharField(max_length=200, verbose_name='Review Title')),
                ('content', models.TextField(verbose_name='Review Content')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Review',
                'verbose_name_plural': 'Course Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='Status')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('progress_percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progress Percentage')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Last Accessed')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('lesson_type', models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('live', 'Live Session')], max_length=20, verbose_name='Lesson Type')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='courses/lessons/videos/', verbose_name='Video File')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (Minutes)')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('is_preview', models.BooleanField(default=False, verbose_name='Is Preview')),
                ('is_required', models.BooleanField(default=True, verbose_name='Is Required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursemodule', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Time spent in seconds', verbose_name='Time Spent')),
                ('last_position', models.PositiveIntegerField(default=0, help_text='Last position in video (seconds)', verbose_name='Last Position')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='courses.enrollment', verbose_name='Enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progress',
            },
        ),
    ]
