# Generated by Django 4.2.24 on 2025-10-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app.courses', '0004_coursepurchase_discount_amount_coursepurchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='allow_download',
            field=models.BooleanField(default=False, verbose_name='Allow Download'),
        ),
    ]
