# Generated by Django 4.2.24 on 2025-11-06 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_update_verbose_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='courses/videos/', verbose_name='فایل ویدیو')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='لینک ویدیو')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت دقیقه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_preview', models.BooleanField(default=False, verbose_name='پیش\u200cنمایش')),
                ('allow_download', models.BooleanField(default=False, verbose_name='اجازه دانلود')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'ویدیو دوره',
                'verbose_name_plural': 'ویدیوهای دوره',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['course', 'order'], name='courses_cou_course__63a654_idx')],
            },
        ),
    ]
