# Generated by Django 4.2.24 on 2025-11-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/videos/attachments/', verbose_name='فایل پیوست'),
        ),
    ]
