# Generated by Django 4.2.24 on 2025-10-11 11:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app.courses', '0005_lesson_allow_download'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app.payment', '0002_alter_cartitem_item_type_alter_orderitem_item_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.CharField(max_length=300, verbose_name='Short Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount Price')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('duration_months', models.PositiveIntegerField(help_text='Estimated time to complete', verbose_name='Duration (Months)')),
                ('language', models.CharField(default='fa', max_length=10, verbose_name='Language')),
                ('prerequisites', models.TextField(blank=True, null=True, verbose_name='Prerequisites')),
                ('learning_objectives', models.TextField(verbose_name='Learning Objectives')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='packages/thumbnails/', verbose_name='Thumbnail')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='packages/videos/', verbose_name='Intro Video')),
                ('purchase_count', models.PositiveIntegerField(default=0, verbose_name='Purchase Count')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Review Count')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, null=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Package Category',
                'verbose_name_plural': 'Package Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackagePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Original Price')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount Amount')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Payment Method')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Purchased At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.order', verbose_name='Order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='packages.package', verbose_name='Package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_purchases', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Package Purchase',
                'verbose_name_plural': 'Package Purchases',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'package')},
            },
        ),
        migrations.CreateModel(
            name='PackageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('title', models.CharField(max_length=200, verbose_name='Review Title')),
                ('content', models.TextField(verbose_name='Review Content')),
                ('value_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Value for Money')),
                ('content_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Content Quality')),
                ('support_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Support Rating')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='packages.packagepurchase', verbose_name='Purchase')),
            ],
            options={
                'verbose_name': 'Package Review',
                'verbose_name_plural': 'Package Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_progress_percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Overall Progress')),
                ('completed_courses', models.PositiveIntegerField(default=0, verbose_name='Completed Courses')),
                ('total_time_spent', models.PositiveIntegerField(default=0, help_text='Time spent in minutes', verbose_name='Total Time Spent')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='packages.packagepurchase', verbose_name='Purchase')),
            ],
            options={
                'verbose_name': 'Package Progress',
                'verbose_name_plural': 'Package Progress',
            },
        ),
        migrations.CreateModel(
            name='PackageCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Coupon Code')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('coupon_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20, verbose_name='Coupon Type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Value')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimum Order Amount')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Discount Amount')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Usage Limit')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Used Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(verbose_name='Valid Until')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_packages', models.ManyToManyField(blank=True, related_name='coupons', to='packages.package', verbose_name='Applicable Packages')),
            ],
            options={
                'verbose_name': 'Package Coupon',
                'verbose_name_plural': 'Package Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='packages.packagecategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='package',
            name='courses',
            field=models.ManyToManyField(related_name='packages', to='courses.course', verbose_name='Courses'),
        ),
        migrations.CreateModel(
            name='PackageEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Last Accessed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_enrollments', to='courses.enrollment', verbose_name='Enrollment')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='packages.packagepurchase', verbose_name='Purchase')),
            ],
            options={
                'verbose_name': 'Package Enrollment',
                'verbose_name_plural': 'Package Enrollments',
                'ordering': ['-created_at'],
                'unique_together': {('purchase', 'enrollment')},
            },
        ),
    ]
