# Generated by Django 4.2.24 on 2025-10-20 14:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_update_verbose_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_update_verbose_names'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at'], 'verbose_name': 'بسته آموزشی', 'verbose_name_plural': 'بسته\u200cهای آموزشی'},
        ),
        migrations.AlterModelOptions(
            name='packagecategory',
            options={'ordering': ['name'], 'verbose_name': 'دسته\u200cبندی پکیج', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای پکیج'},
        ),
        migrations.AlterModelOptions(
            name='packagecoupon',
            options={'ordering': ['-created_at'], 'verbose_name': 'کوپن پکیج', 'verbose_name_plural': 'کوپن\u200cهای پکیج'},
        ),
        migrations.AlterModelOptions(
            name='packageenrollment',
            options={'ordering': ['-created_at'], 'verbose_name': 'ثبت\u200cنام پکیج', 'verbose_name_plural': 'ثبت\u200cنام\u200cهای پکیج'},
        ),
        migrations.AlterModelOptions(
            name='packageprogress',
            options={'verbose_name': 'پیشرفت پکیج', 'verbose_name_plural': 'پیشرفت\u200cهای پکیج'},
        ),
        migrations.AlterModelOptions(
            name='packagepurchase',
            options={'ordering': ['-purchased_at'], 'verbose_name': 'خرید پکیج', 'verbose_name_plural': 'خریدهای پکیج'},
        ),
        migrations.AlterModelOptions(
            name='packagereview',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر پکیج', 'verbose_name_plural': 'نظرات پکیج'},
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='packages.packagecategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='package',
            name='courses',
            field=models.ManyToManyField(related_name='packages', to='courses.course', verbose_name='دوره\u200cها'),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='package',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت تخفیف'),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration_months',
            field=models.PositiveIntegerField(help_text='زمان تخمینی تکمیل', verbose_name='مدت ماه'),
        ),
        migrations.AlterField(
            model_name='package',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='packages/videos/', verbose_name='ویدیو معرفی'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='ویژه'),
        ),
        migrations.AlterField(
            model_name='package',
            name='language',
            field=models.CharField(default='fa', max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='package',
            name='learning_objectives',
            field=models.TextField(verbose_name='اهداف یادگیری'),
        ),
        migrations.AlterField(
            model_name='package',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='package',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان متا'),
        ),
        migrations.AlterField(
            model_name='package',
            name='prerequisites',
            field=models.TextField(blank=True, null=True, verbose_name='پیش\u200cنیازها'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='package',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='package',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد خرید'),
        ),
        migrations.AlterField(
            model_name='package',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='package',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد نظر'),
        ),
        migrations.AlterField(
            model_name='package',
            name='short_description',
            field=models.CharField(max_length=300, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='package',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='packages/thumbnails/', verbose_name='تصویر کوچک'),
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='package',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='color',
            field=models.CharField(default='#007bff', help_text='Hex color code', max_length=7, verbose_name='کد رنگ هگز'),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, null=True, verbose_name='کلاس آیکون Font Awesome'),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='packagecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='packagecoupon',
            name='applicable_packages',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='packages.package', verbose_name='پکیج\u200cهای قابل اعمال'),
        ),
        migrations.AlterField(
            model_name='packagecoupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='کد کوپن'),
        ),
        migrations.AlterField(
            model_name='packagecoupon',
            name='coupon_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20, verbose_name='نوع کوپن'),
        ),
        migrations.AlterField(
            model_name='packagecoupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='packagecoupon',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='packagecoupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار تخفیف'),
        ),
        migrations.AlterField(
            model_name='packagecoupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='packagecoupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='حداکثر مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='packagecoupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حداقل مبلغ سفارش'),
        ),
        migrations.AlterField(
            model_name='packagecoupon',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='packagecoupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='packagecoupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حد استفاده'),
        ),
        migrations.AlterField(
            model_name='packagecoupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده'),
        ),
        migrations.AlterField(
            model_name='packagecoupon',
            name='valid_from',
            field=models.DateTimeField(verbose_name='معتبر از'),
        ),
        migrations.AlterField(
            model_name='packagecoupon',
            name='valid_until',
            field=models.DateTimeField(verbose_name='معتبر تا'),
        ),
        migrations.AlterField(
            model_name='packageenrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='packageenrollment',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_enrollments', to='courses.enrollment', verbose_name='ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='packageenrollment',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین دسترسی'),
        ),
        migrations.AlterField(
            model_name='packageenrollment',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='packages.packagepurchase', verbose_name='خرید'),
        ),
        migrations.AlterField(
            model_name='packageenrollment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شروع شده در'),
        ),
        migrations.AlterField(
            model_name='packageenrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='packageprogress',
            name='completed_courses',
            field=models.PositiveIntegerField(default=0, verbose_name='دوره\u200cهای تکمیل شده'),
        ),
        migrations.AlterField(
            model_name='packageprogress',
            name='overall_progress_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='پیشرفت کلی'),
        ),
        migrations.AlterField(
            model_name='packageprogress',
            name='purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='packages.packagepurchase', verbose_name='خرید'),
        ),
        migrations.AlterField(
            model_name='packageprogress',
            name='total_time_spent',
            field=models.PositiveIntegerField(default=0, help_text='Time spent in minutes', verbose_name='کل زمان صرف شده'),
        ),
        migrations.AlterField(
            model_name='packageprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت اصلی'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='packages.package', verbose_name='پکیج'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='payment_method',
            field=models.CharField(max_length=50, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تراکنش'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_purchases', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='content',
            field=models.TextField(verbose_name='محتوای نظر'),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='content_rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='کیفیت محتوا'),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تأیید شده'),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='packages.packagepurchase', verbose_name='خرید'),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='support_rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز پشتیبانی'),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان نظر'),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='value_rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='ارزش پول'),
        ),
    ]
