# Generated by Django 4.2.24 on 2025-11-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_update_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at'], 'verbose_name': 'پکیج آموزشی', 'verbose_name_plural': 'پکیج\u200cهای آموزشی'},
        ),
    ]
