# Generated by Django 4.2.24 on 2025-12-19 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0003_alter_package_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد لایک'),
        ),
        migrations.CreateModel(
            name='PackageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوای')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_comments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='packages.package', verbose_name='پکیج')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='packages.packagecomment', verbose_name='نظر والد')),
            ],
            options={
                'verbose_name': 'نظر پکیج',
                'verbose_name_plural': 'نظرات پکیج',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='packages.package', verbose_name='پکیج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_likes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لایک پکیج',
                'verbose_name_plural': 'لایک\u200cهای پکیج',
                'unique_together': {('package', 'user')},
            },
        ),
    ]
