# Generated by Django 4.2.24 on 2025-10-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app.payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item_type',
            field=models.CharField(choices=[('course', 'Course'), ('test', 'Test'), ('session', 'Session'), ('package', 'Package'), ('workshop', 'Workshop')], max_length=20, verbose_name='Item Type'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('course', 'Course'), ('test', 'Test'), ('session', 'Session'), ('package', 'Package'), ('workshop', 'Workshop')], max_length=20, verbose_name='Item Type'),
        ),
        migrations.CreateModel(
            name='InstallmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_installments', models.PositiveIntegerField(verbose_name='Total Installments')),
                ('current_installment', models.PositiveIntegerField(default=0, verbose_name='Current Installment')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Next Due Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_schedule', to='payment.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Installment Schedule',
                'verbose_name_plural': 'Installment Schedules',
            },
        ),
    ]
