# Generated by Django 4.2.24 on 2025-11-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_update_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('course', 'Course'), ('test', 'Test'), ('session', 'Session'), ('package', 'Package'), ('workshop', 'Workshop'), ('appointment_deposit', 'Appointment Deposit')], max_length=20, verbose_name='نوع آیتم'),
        ),
    ]
