# Generated by Django 4.2.24 on 2025-12-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_orderitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='برای ذخیره اطلاعات اضافی مثل payment_type برای کارگاه\u200cها', verbose_name='اطلاعات اضافی'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='برای ذخیره اطلاعات اضافی مثل payment_type برای کارگاه\u200cها', verbose_name='اطلاعات اضافی'),
        ),
    ]
