# Generated by Django 4.2.24 on 2026-06-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_wallet_wallettransaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='payment_wal_wallet__a9c1b7_idx',
            old_name='payment_wal_wallet__idx',
        ),
        migrations.RenameIndex(
            model_name='wallettransaction',
            new_name='payment_wal_transac_bee649_idx',
            old_name='payment_wal_transac_idx',
        ),
    ]
