# Generated by Django 4.2.24 on 2025-10-20 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name'], 'verbose_name': 'موسسه', 'verbose_name_plural': 'موسسات'},
        ),
        migrations.AlterModelOptions(
            name='institutionorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'سفارش موسسه', 'verbose_name_plural': 'سفارشات موسسه'},
        ),
        migrations.AlterModelOptions(
            name='institutionpayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'پرداخت موسسه', 'verbose_name_plural': 'پرداخت\u200cهای موسسه'},
        ),
        migrations.AlterModelOptions(
            name='institutionsubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'اشتراک موسسه', 'verbose_name_plural': 'اشتراک\u200cهای موسسه'},
        ),
        migrations.AlterModelOptions(
            name='institutionuser',
            options={'verbose_name': 'کاربر موسسه', 'verbose_name_plural': 'کاربران موسسه'},
        ),
        migrations.AlterModelOptions(
            name='servicepackage',
            options={'ordering': ['package_type', 'price'], 'verbose_name': 'پکیج خدمات', 'verbose_name_plural': 'پکیج\u200cهای خدمات'},
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='contact_person',
            field=models.CharField(max_length=100, verbose_name='شخص تماس'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(choices=[('university', 'University'), ('school', 'School'), ('clinic', 'Clinic'), ('hospital', 'Hospital'), ('company', 'Company'), ('ngo', 'NGO'), ('government', 'Government'), ('other', 'Other')], max_length=20, verbose_name='نوع موسسه'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تأیید شده'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت'),
        ),
        migrations.AlterField(
            model_name='institutionorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید'),
        ),
        migrations.AlterField(
            model_name='institutionorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL, verbose_name='تأیید شده توسط'),
        ),
        migrations.AlterField(
            model_name='institutionorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='institutionorder',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sales.institution', verbose_name='موسسه'),
        ),
        migrations.AlterField(
            model_name='institutionorder',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها'),
        ),
        migrations.AlterField(
            model_name='institutionorder',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sales.servicepackage', verbose_name='پکیج'),
        ),
        migrations.AlterField(
            model_name='institutionorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='institutionorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='institutionorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='institutionorder',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='institutionorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='institutionpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='institutionpayment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل'),
        ),
        migrations.AlterField(
            model_name='institutionpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='institutionpayment',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.institution', verbose_name='موسسه'),
        ),
        migrations.AlterField(
            model_name='institutionpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.institutionorder', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='institutionpayment',
            name='payment_method',
            field=models.CharField(max_length=50, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='institutionpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='institutionpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تراکنش'),
        ),
        migrations.AlterField(
            model_name='institutionpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='institutionsubscription',
            name='courses_used',
            field=models.PositiveIntegerField(default=0, verbose_name='دوره\u200cهای استفاده شده'),
        ),
        migrations.AlterField(
            model_name='institutionsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='institutionsubscription',
            name='current_users',
            field=models.PositiveIntegerField(default=0, verbose_name='کاربران فعلی'),
        ),
        migrations.AlterField(
            model_name='institutionsubscription',
            name='end_date',
            field=models.DateField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='institutionsubscription',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='sales.institution', verbose_name='موسسه'),
        ),
        migrations.AlterField(
            model_name='institutionsubscription',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='sales.servicepackage', verbose_name='پکیج'),
        ),
        migrations.AlterField(
            model_name='institutionsubscription',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='institutionsubscription',
            name='sessions_used',
            field=models.PositiveIntegerField(default=0, verbose_name='جلسات استفاده شده'),
        ),
        migrations.AlterField(
            model_name='institutionsubscription',
            name='start_date',
            field=models.DateField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='institutionsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='institutionsubscription',
            name='tests_used',
            field=models.PositiveIntegerField(default=0, verbose_name='تست\u200cهای استفاده شده'),
        ),
        migrations.AlterField(
            model_name='institutionsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='institutionuser',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_users', to='sales.institution', verbose_name='موسسه'),
        ),
        migrations.AlterField(
            model_name='institutionuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='institutionuser',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت'),
        ),
        migrations.AlterField(
            model_name='institutionuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('user', 'User'), ('viewer', 'Viewer')], default='user', max_length=20, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='institutionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_memberships', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='duration_months',
            field=models.PositiveIntegerField(verbose_name='مدت ماه'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='features',
            field=models.JSONField(default=list, verbose_name='ویژگی\u200cها'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='max_courses',
            field=models.PositiveIntegerField(verbose_name='حداکثر دوره\u200cها'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='max_sessions',
            field=models.PositiveIntegerField(verbose_name='حداکثر جلسات'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='max_tests',
            field=models.PositiveIntegerField(verbose_name='حداکثر تست\u200cها'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='max_users',
            field=models.PositiveIntegerField(verbose_name='حداکثر کاربران'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='package_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], max_length=20, verbose_name='نوع پکیج'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
