from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from django.db import transaction
import os

User = get_user_model()

class Command(BaseCommand):
    help = 'Populate therapists from provided images data'

    def handle(self, *args, **options):
        self.stdout.write('Creating therapists from image data...')
        
        # Therapist data extracted from the provided images
        therapists_data = [
            {
                'email': 'dr.emami.doost@example.com',
                'first_name': 'دکتر سید مجتبی',
                'last_name': 'امامی دوست',
                'user_type': 'therapist',
                'phone_number': '09123456001',
                'specialization': 'بزرگسال، سوپروایزر طرحواره درمانی، کوچینگ فردی',
                'license_number': 'PSY001',
                'experience_years': 15,
                'hourly_rate': 200000,
                'bio': 'دکتری تخصصی روان شناسی، صاحب امتیاز و مسئول فنی مرکز مشاوره سرمد، مدیریت و مسئول فنی کلینیک روان شناسی دانشکده روان شناسی دانشگاه تهران، مدرس دانشگاه و دوره های تخصصی روان شناسی',
                'is_verified': True,
                'is_available': True,
                'gender': 'M',
            },
            {
                'email': 'dr.mohsen.emami@example.com',
                'first_name': 'دکتر سید محسن',
                'last_name': 'امامی دوست',
                'user_type': 'therapist',
                'phone_number': '09123456002',
                'specialization': 'بزرگسال، کوچینگ فردی، سلامت، درمانگر بالینی، روان شناسی کسب و کار',
                'license_number': 'PSY002',
                'experience_years': 12,
                'hourly_rate': 180000,
                'bio': 'دکتری تخصصی روان شناسی سلامت دانشگاه تهران، هیئت علمی دانشگاه، سوپروایزر کشوری مداخله در خودکشی، مدرس دانشگاه و دوره های تخصصی روان شناسی',
                'is_verified': True,
                'is_available': True,
                'gender': 'M',
            },
            {
                'email': 'dr.jaberzadeh@example.com',
                'first_name': 'دکتر',
                'last_name': 'شقایق جابرزاده انصاری',
                'user_type': 'therapist',
                'phone_number': '09123456003',
                'specialization': 'کودک و نوجوان',
                'license_number': 'PSY003',
                'experience_years': 8,
                'hourly_rate': 160000,
                'bio': 'دکتری تخصصی روان شناسی کودک دانشگاه تهران، مدرس دانشگاه و دوره های تخصصی روان شناسی',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            },
            {
                'email': 'atefeh.fadaei@example.com',
                'first_name': 'عاطفه',
                'last_name': 'فدایی',
                'user_type': 'therapist',
                'phone_number': '09123456004',
                'specialization': 'بزرگسال، روان شناسی ورزشی',
                'license_number': 'PSY004',
                'experience_years': 6,
                'hourly_rate': 140000,
                'bio': 'کارشناسی ارشد روان شناسی بالینی',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            },
            {
                'email': 'maedeh.ahmadi@example.com',
                'first_name': 'مائده',
                'last_name': 'احمدی',
                'user_type': 'therapist',
                'phone_number': '09123456005',
                'specialization': 'کودک',
                'license_number': 'PSY005',
                'experience_years': 5,
                'hourly_rate': 130000,
                'bio': 'کارشناسی ارشد مشاوره و راهنمایی، مدرس دوره های روان شناسی',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            },
            {
                'email': 'najmeh.alinaghian@example.com',
                'first_name': 'نجمه',
                'last_name': 'علی نقیان',
                'user_type': 'therapist',
                'phone_number': '09123456006',
                'specialization': 'خانواده، زوج، پیش از ازدواج',
                'license_number': 'PSY006',
                'experience_years': 10,
                'hourly_rate': 170000,
                'bio': 'مقطع دکتری تخصصی روانشناسی عمومی، مشاور قوه قضائیه',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            },
            {
                'email': 'dr.mokhtari@example.com',
                'first_name': 'دکتر',
                'last_name': 'سمانه مختاری',
                'user_type': 'therapist',
                'phone_number': '09123456007',
                'specialization': 'بزرگسال، خانواده، زوج و پیش از ازدواج',
                'license_number': 'PSY007',
                'experience_years': 12,
                'hourly_rate': 190000,
                'bio': 'دکتری تخصصی مشاوره، هیئت علمی دانشگاه، مدرس دانشگاه و دوره های تخصصی روان شناسی',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            },
            {
                'email': 'mahsa.sharif@example.com',
                'first_name': 'مهسا',
                'last_name': 'شریف',
                'user_type': 'therapist',
                'phone_number': '09123456008',
                'specialization': 'بزرگسال',
                'license_number': 'PSY008',
                'experience_years': 7,
                'hourly_rate': 150000,
                'bio': 'کارشناسی ارشد روان شناسی بالینی، مسئول فنی مرکز مشاوره سرمد، مدرس دوره های روان شناسی',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            },
            {
                'email': 'morteza.javanmard@example.com',
                'first_name': 'مرتضی',
                'last_name': 'جوانمرد',
                'user_type': 'therapist',
                'phone_number': '09123456009',
                'specialization': 'بزرگسال، تحصیلی، شغلی و اعتیاد',
                'license_number': 'PSY009',
                'experience_years': 9,
                'hourly_rate': 160000,
                'bio': 'کارشناسی ارشد روان شناسی عمومی، سرگروه مشاوران آموزش و پرورش استان',
                'is_verified': True,
                'is_available': True,
                'gender': 'M',
            },
            {
                'email': 'mahdieh.hesam@example.com',
                'first_name': 'مهدیه',
                'last_name': 'حسام',
                'user_type': 'therapist',
                'phone_number': '09123456010',
                'specialization': 'بزرگسال',
                'license_number': 'PSY010',
                'experience_years': 6,
                'hourly_rate': 140000,
                'bio': 'کارشناسی ارشد مشاوره، مدرس دوره های روان شناسی',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            },
            {
                'email': 'mina.ghaderi@example.com',
                'first_name': 'مینا',
                'last_name': 'قادری',
                'user_type': 'therapist',
                'phone_number': '09123456011',
                'specialization': 'بزرگسال، مشکلات عملکرد و کارکرد جنسی',
                'license_number': 'PSY011',
                'experience_years': 8,
                'hourly_rate': 160000,
                'bio': 'کارشناسی ارشد روان شناسی بالینی',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            },
            {
                'email': 'mona.rahnamaee@example.com',
                'first_name': 'مونا',
                'last_name': 'رهنمایی',
                'user_type': 'therapist',
                'phone_number': '09123456012',
                'specialization': 'کودک',
                'license_number': 'PSY012',
                'experience_years': 5,
                'hourly_rate': 130000,
                'bio': 'کارشناسی ارشد روان شناسی عمومی',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            },
            {
                'email': 'dr.pourabadi@example.com',
                'first_name': 'دکتر',
                'last_name': 'پریسا پورآبادی',
                'user_type': 'therapist',
                'phone_number': '09123456013',
                'specialization': 'کودک، نوجوان و توان بخشی شناختی',
                'license_number': 'PSY013',
                'experience_years': 11,
                'hourly_rate': 180000,
                'bio': 'دکتری روان شناسی عمومی، استاد دانشگاه، مدرس دوره های آموزشی روان شناسی',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            },
            {
                'email': 'habibollah.pasyar@example.com',
                'first_name': 'حبیب اله',
                'last_name': 'پاسیار',
                'user_type': 'therapist',
                'phone_number': '09123456014',
                'specialization': 'کودک، نوجوان و بزرگسال',
                'license_number': 'PSY014',
                'experience_years': 7,
                'hourly_rate': 150000,
                'bio': 'کارشناسی ارشد روان شناسی عمومی',
                'is_verified': True,
                'is_available': True,
                'gender': 'M',
            },
            {
                'email': 'marjan.chavooshi@example.com',
                'first_name': 'مرجان',
                'last_name': 'چاووشی',
                'user_type': 'therapist',
                'phone_number': '09123456015',
                'specialization': 'بزرگسال، خانواده و پیش از ازدواج',
                'license_number': 'PSY015',
                'experience_years': 9,
                'hourly_rate': 170000,
                'bio': 'کارشناسی ارشد روان شناسی بالینی',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            },
            {
                'email': 'mina.hojjati@example.com',
                'first_name': 'مینا',
                'last_name': 'حجتی',
                'user_type': 'therapist',
                'phone_number': '09123456016',
                'specialization': 'بزرگسال',
                'license_number': 'PSY016',
                'experience_years': 6,
                'hourly_rate': 140000,
                'bio': 'کارشناسی ارشد روان شناسی بالینی، مدرس دوره های روان شناسی',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            },
            {
                'email': 'dr.ghanbarian@example.com',
                'first_name': 'دکتر',
                'last_name': 'سپیده قنبریان',
                'user_type': 'therapist',
                'phone_number': '09123456017',
                'specialization': 'کودک و نوجوان',
                'license_number': 'PSY017',
                'experience_years': 10,
                'hourly_rate': 180000,
                'bio': 'دکتری تخصصی مشاوره کارشناس نظام روان شناسی و مشاوره، مشاور مدارس',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            },
            {
                'email': 'mohaddeseh.bakhshi@example.com',
                'first_name': 'محدثه',
                'last_name': 'بخشی',
                'user_type': 'therapist',
                'phone_number': '09123456018',
                'specialization': 'بزرگسال',
                'license_number': 'PSY018',
                'experience_years': 5,
                'hourly_rate': 130000,
                'bio': 'کارشناسی ارشد روان شناسی عمومی',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            },
            {
                'email': 'marzieh.kazemi@example.com',
                'first_name': 'مرضیه',
                'last_name': 'کاظمی',
                'user_type': 'therapist',
                'phone_number': '09123456019',
                'specialization': 'کودک',
                'license_number': 'PSY019',
                'experience_years': 6,
                'hourly_rate': 140000,
                'bio': 'کارشناسی ارشد مشاوره خانواده، مدرس دوره های روان شناسی، مشاور مدارس',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            },
            {
                'email': 'laleh.tanbakouyi@example.com',
                'first_name': 'لاله',
                'last_name': 'تنباکویی',
                'user_type': 'therapist',
                'phone_number': '09123456020',
                'specialization': 'کودک',
                'license_number': 'PSY020',
                'experience_years': 7,
                'hourly_rate': 150000,
                'bio': 'کارشناسی ارشد روان شناسی تربیتی، مشاور مدارس، مدرس دوره های روان شناسی',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            },
            {
                'email': 'kowsar.moradi@example.com',
                'first_name': 'کوثر',
                'last_name': 'مرادی',
                'user_type': 'therapist',
                'phone_number': '09123456021',
                'specialization': 'کودک و نوجوان',
                'license_number': 'PSY021',
                'experience_years': 8,
                'hourly_rate': 160000,
                'bio': 'کارشناسی ارشد روان شناسی بالینی، مشاور مدارس، مدرس دوره های روان شناسی',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            },
            {
                'email': 'narges.kashmirshakan@example.com',
                'first_name': 'نرگس',
                'last_name': 'کشمیرشکن',
                'user_type': 'therapist',
                'phone_number': '09123456022',
                'specialization': 'بزرگسال',
                'license_number': 'PSY022',
                'experience_years': 6,
                'hourly_rate': 140000,
                'bio': 'کارشناسی ارشد روانشناسی شخصیت',
                'is_verified': True,
                'is_available': True,
                'gender': 'F',
            }
        ]
        
        created_count = 0
        updated_count = 0
        
        with transaction.atomic():
            for therapist_data in therapists_data:
                user, created = User.objects.get_or_create(
                    email=therapist_data['email'],
                    defaults=therapist_data
                )
                
                if created:
                    user.set_password('password123')
                    user.save()
                    created_count += 1
                    self.stdout.write(
                        self.style.SUCCESS(f'Created therapist: {user.full_name}')
                    )
                else:
                    # Update existing therapist with new data
                    for key, value in therapist_data.items():
                        if key != 'email':
                            setattr(user, key, value)
                    user.save()
                    updated_count += 1
                    self.stdout.write(
                        self.style.WARNING(f'Updated therapist: {user.full_name}')
                    )
        
        self.stdout.write(
            self.style.SUCCESS(
                f'Successfully processed {len(therapists_data)} therapists: '
                f'{created_count} created, {updated_count} updated'
            )
        )
