# Generated by Django 4.2.24 on 2025-10-11 11:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app.payment', '0002_alter_cartitem_item_type_alter_orderitem_item_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.CharField(max_length=300, verbose_name='Short Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('registration_open', 'Registration Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, verbose_name='Difficulty')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('registration_deadline', models.DateTimeField(verbose_name='Registration Deadline')),
                ('max_participants', models.PositiveIntegerField(default=50, verbose_name='Maximum Participants')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Current Participants')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount Price')),
                ('payment_type', models.CharField(choices=[('full_payment', 'Full Payment'), ('installment', 'Installment Payment'), ('both', 'Both Options')], default='both', max_length=20, verbose_name='Payment Type')),
                ('installment_months', models.PositiveIntegerField(default=3, verbose_name='Number of Installment Months')),
                ('total_hours', models.PositiveIntegerField(verbose_name='Total Hours')),
                ('language', models.CharField(default='fa', max_length=10, verbose_name='Language')),
                ('prerequisites', models.TextField(blank=True, null=True, verbose_name='Prerequisites')),
                ('learning_objectives', models.TextField(verbose_name='Learning Objectives')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='workshops/thumbnails/', verbose_name='Thumbnail')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='workshops/videos/', verbose_name='Intro Video')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Review Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, null=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Workshop Category',
                'verbose_name_plural': 'Workshop Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='pending_payment', max_length=20, verbose_name='Status')),
                ('payment_type', models.CharField(choices=[('full_payment', 'Full Payment'), ('installment', 'Installment Payment')], max_length=20, verbose_name='Payment Type')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Paid')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Last Accessed')),
                ('progress_percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progress Percentage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registrations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='workshops.workshop', verbose_name='Workshop')),
            ],
            options={
                'verbose_name': 'Workshop Registration',
                'verbose_name_plural': 'Workshop Registrations',
                'ordering': ['-registered_at'],
                'unique_together': {('user', 'workshop')},
            },
        ),
        migrations.CreateModel(
            name='WorkshopSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField(verbose_name='Session Number')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('scheduled_datetime', models.DateTimeField(verbose_name='Scheduled Date & Time')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duration (Minutes)')),
                ('meeting_link', models.URLField(blank=True, null=True, verbose_name='Meeting Link')),
                ('meeting_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meeting ID')),
                ('meeting_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Meeting Password')),
                ('recording_url', models.URLField(blank=True, null=True, verbose_name='Recording URL')),
                ('materials', models.TextField(blank=True, null=True, verbose_name='Session Materials')),
                ('homework', models.TextField(blank=True, null=True, verbose_name='Homework')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workshops.workshop', verbose_name='Workshop')),
            ],
            options={
                'verbose_name': 'Workshop Session',
                'verbose_name_plural': 'Workshop Sessions',
                'ordering': ['workshop', 'session_number'],
                'unique_together': {('workshop', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='WorkshopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('title', models.CharField(max_length=200, verbose_name='Review Title')),
                ('content', models.TextField(verbose_name='Review Content')),
                ('instructor_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Instructor Rating')),
                ('content_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Content Rating')),
                ('interaction_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Interaction Rating')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='workshops.workshopregistration', verbose_name='Registration')),
            ],
            options={
                'verbose_name': 'Workshop Review',
                'verbose_name_plural': 'Workshop Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workshop',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='workshops.workshopcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_workshops', to=settings.AUTH_USER_MODEL, verbose_name='Instructor'),
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('number_of_installments', models.PositiveIntegerField(verbose_name='Number of Installments')),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Installment Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plan', to='workshops.workshopregistration', verbose_name='Registration')),
            ],
            options={
                'verbose_name': 'Installment Plan',
                'verbose_name_plural': 'Installment Plans',
            },
        ),
        migrations.CreateModel(
            name='WorkshopSessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False, verbose_name='Attended')),
                ('attendance_marked_at', models.DateTimeField(blank=True, null=True, verbose_name='Attendance Marked At')),
                ('join_time', models.DateTimeField(blank=True, null=True, verbose_name='Join Time')),
                ('leave_time', models.DateTimeField(blank=True, null=True, verbose_name='Leave Time')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duration (Minutes)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendance', to='workshops.workshopregistration', verbose_name='Registration')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='workshops.workshopsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Workshop Session Attendance',
                'verbose_name_plural': 'Workshop Session Attendances',
                'ordering': ['session__scheduled_datetime'],
                'unique_together': {('registration', 'session')},
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='Installment Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Reminder Sent')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Reminder Sent At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.order', verbose_name='Order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='workshops.installmentplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Installment Payment',
                'verbose_name_plural': 'Installment Payments',
                'ordering': ['plan', 'installment_number'],
                'unique_together': {('plan', 'installment_number')},
            },
        ),
    ]
