# Generated by Django 4.2.24 on 2025-10-20 15:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_update_verbose_names'),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installmentpayment',
            options={'ordering': ['plan', 'installment_number'], 'verbose_name': 'پرداخت اقساط', 'verbose_name_plural': 'پرداخت\u200cهای اقساط'},
        ),
        migrations.AlterModelOptions(
            name='installmentplan',
            options={'verbose_name': 'برنامه اقساط', 'verbose_name_plural': 'برنامه\u200cهای اقساط'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ['-created_at'], 'verbose_name': 'کارگاه', 'verbose_name_plural': 'کارگاه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='workshopcategory',
            options={'ordering': ['name'], 'verbose_name': 'دسته\u200cبندی کارگاه', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای کارگاه'},
        ),
        migrations.AlterModelOptions(
            name='workshopregistration',
            options={'ordering': ['-registered_at'], 'verbose_name': 'ثبت\u200cنام کارگاه', 'verbose_name_plural': 'ثبت\u200cنام\u200cهای کارگاه'},
        ),
        migrations.AlterModelOptions(
            name='workshopreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر کارگاه', 'verbose_name_plural': 'نظرات کارگاه'},
        ),
        migrations.AlterModelOptions(
            name='workshopsession',
            options={'ordering': ['workshop', 'session_number'], 'verbose_name': 'جلسه کارگاه', 'verbose_name_plural': 'جلسات کارگاه'},
        ),
        migrations.AlterModelOptions(
            name='workshopsessionattendance',
            options={'ordering': ['session__scheduled_datetime'], 'verbose_name': 'حضور جلسه کارگاه', 'verbose_name_plural': 'حضورهای جلسه کارگاه'},
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='due_date',
            field=models.DateField(verbose_name='تاریخ سررسید'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='installment_number',
            field=models.PositiveIntegerField(verbose_name='شماره قسط'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='پرداخت شده در'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='workshops.installmentplan', verbose_name='برنامه'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='یادآوری ارسال شده'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='یادآوری ارسال شده در'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تراکنش'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ قسط'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='number_of_installments',
            field=models.PositiveIntegerField(verbose_name='تعداد اقساط'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plan', to='workshops.workshopregistration', verbose_name='ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='workshops.workshopcategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='current_participants',
            field=models.PositiveIntegerField(default=0, verbose_name='شرکت\u200cکنندگان فعلی'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, verbose_name='سطح دشواری'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت تخفیف'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='end_date',
            field=models.DateField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='installment_months',
            field=models.PositiveIntegerField(default=3, verbose_name='تعداد ماه\u200cهای اقساط'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_workshops', to=settings.AUTH_USER_MODEL, verbose_name='مدرس'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='workshops/videos/', verbose_name='ویدیو معرفی'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='language',
            field=models.CharField(default='fa', max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='learning_objectives',
            field=models.TextField(verbose_name='اهداف یادگیری'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='max_participants',
            field=models.PositiveIntegerField(default=50, verbose_name='حداکثر شرکت\u200cکنندگان'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='payment_type',
            field=models.CharField(choices=[('full_payment', 'Full Payment'), ('installment', 'Installment Payment'), ('both', 'Both Options')], default='both', max_length=20, verbose_name='نوع پرداخت'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='prerequisites',
            field=models.TextField(blank=True, null=True, verbose_name='پیش\u200cنیازها'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='registration_deadline',
            field=models.DateTimeField(verbose_name='مهلت ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد نظرات'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='short_description',
            field=models.CharField(max_length=300, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='start_date',
            field=models.DateField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('registration_open', 'Registration Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='workshops/thumbnails/', verbose_name='تصویر کوچک'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='total_hours',
            field=models.PositiveIntegerField(verbose_name='مجموع ساعات'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='workshopcategory',
            name='color',
            field=models.CharField(default='#007bff', help_text='Hex color code', max_length=7, verbose_name='کد رنگ هگز'),
        ),
        migrations.AlterField(
            model_name='workshopcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='workshopcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='workshopcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, null=True, verbose_name='کلاس آیکون Font Awesome'),
        ),
        migrations.AlterField(
            model_name='workshopcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='workshopcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='workshopcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تکمیل شده در'),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین دسترسی'),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='payment_type',
            field=models.CharField(choices=[('full_payment', 'Full Payment'), ('installment', 'Installment Payment')], max_length=20, verbose_name='نوع پرداخت'),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='progress_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد پیشرفت'),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ثبت\u200cنام شده در'),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='pending_payment', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registrations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='workshops.workshop', verbose_name='کارگاه'),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='content',
            field=models.TextField(verbose_name='محتوای نظر'),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='content_rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز محتوا'),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='instructor_rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز مدرس'),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='interaction_rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز تعامل'),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تأیید شده'),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='workshops.workshopregistration', verbose_name='ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان نظر'),
        ),
        migrations.AlterField(
            model_name='workshopreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='workshopsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تکمیل شده در'),
        ),
        migrations.AlterField(
            model_name='workshopsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='workshopsession',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='workshopsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(verbose_name='مدت دقیقه'),
        ),
        migrations.AlterField(
            model_name='workshopsession',
            name='homework',
            field=models.TextField(blank=True, null=True, verbose_name='تکلیف'),
        ),
        migrations.AlterField(
            model_name='workshopsession',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='تکمیل شده'),
        ),
        migrations.AlterField(
            model_name='workshopsession',
            name='materials',
            field=models.TextField(blank=True, null=True, verbose_name='مواد جلسه'),
        ),
        migrations.AlterField(
            model_name='workshopsession',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه جلسه'),
        ),
        migrations.AlterField(
            model_name='workshopsession',
            name='meeting_link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک جلسه'),
        ),
        migrations.AlterField(
            model_name='workshopsession',
            name='meeting_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رمز عبور جلسه'),
        ),
        migrations.AlterField(
            model_name='workshopsession',
            name='recording_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک ضبط'),
        ),
        migrations.AlterField(
            model_name='workshopsession',
            name='scheduled_datetime',
            field=models.DateTimeField(verbose_name='تاریخ و زمان برنامه\u200cریزی شده'),
        ),
        migrations.AlterField(
            model_name='workshopsession',
            name='session_number',
            field=models.PositiveIntegerField(verbose_name='شماره جلسه'),
        ),
        migrations.AlterField(
            model_name='workshopsession',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='workshopsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='workshopsession',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workshops.workshop', verbose_name='کارگاه'),
        ),
        migrations.AlterField(
            model_name='workshopsessionattendance',
            name='attendance_marked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='حضور ثبت شده در'),
        ),
        migrations.AlterField(
            model_name='workshopsessionattendance',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='حاضر'),
        ),
        migrations.AlterField(
            model_name='workshopsessionattendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='workshopsessionattendance',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='مدت دقیقه'),
        ),
        migrations.AlterField(
            model_name='workshopsessionattendance',
            name='join_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ورود'),
        ),
        migrations.AlterField(
            model_name='workshopsessionattendance',
            name='leave_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج'),
        ),
        migrations.AlterField(
            model_name='workshopsessionattendance',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها'),
        ),
        migrations.AlterField(
            model_name='workshopsessionattendance',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendance', to='workshops.workshopregistration', verbose_name='ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='workshopsessionattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='workshops.workshopsession', verbose_name='جلسه'),
        ),
        migrations.AlterField(
            model_name='workshopsessionattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
