# Generated by Django 4.2.24 on 2025-10-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_alter_installmentpayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopsession',
            name='croom_platform_link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک پلتفرم سی\u200cروم'),
        ),
        migrations.AddField(
            model_name='workshopsession',
            name='session_video',
            field=models.FileField(blank=True, null=True, upload_to='workshops/session_videos/', verbose_name='ویدیو جلسه'),
        ),
    ]
