# Generated by Django 4.2.24 on 2025-10-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_workshopsession_croom_platform_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopsession',
            name='meeting_id',
        ),
        migrations.RemoveField(
            model_name='workshopsession',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='workshopsession',
            name='meeting_password',
        ),
        migrations.RemoveField(
            model_name='workshopsession',
            name='recording_url',
        ),
    ]
