# Generated by Django 4.2.24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshops', '0004_remove_workshopsession_meeting_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='شماره گواهینامه')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('revoked', 'Revoked')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='workshops/certificates/', verbose_name='فایل گواهینامه')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ صدور')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('revocation_reason', models.TextField(blank=True, null=True, verbose_name='دلیل لغو')),
                ('verification_code', models.CharField(max_length=32, unique=True, verbose_name='کد تأیید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL, verbose_name='صادرکننده')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='workshops.workshopregistration', verbose_name='ثبت\u200cنام')),
            ],
            options={
                'verbose_name': 'گواهینامه کارگاه',
                'verbose_name_plural': 'گواهینامه\u200cهای کارگاه',
                'ordering': ['-issued_at', '-created_at'],
            },
        ),
    ]

