# Generated by Django 4.2.24 on 2025-10-20 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'رویداد تحلیل', 'verbose_name_plural': 'رویدادهای تحلیل'},
        ),
        migrations.AlterModelOptions(
            name='dashboardwidget',
            options={'ordering': ['position_y', 'position_x'], 'verbose_name': 'ویجت داشبورد', 'verbose_name_plural': 'ویجت\u200cهای داشبورد'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-generated_at'], 'verbose_name': 'گزارش', 'verbose_name_plural': 'گزارش\u200cها'},
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_data',
            field=models.JSONField(default=dict, verbose_name='داده\u200cهای رویداد'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('course_enrollment', 'Course Enrollment'), ('test_completion', 'Test Completion'), ('session_booking', 'Session Booking'), ('payment', 'Payment'), ('user_registration', 'User Registration'), ('login', 'Login'), ('logout', 'Logout')], max_length=30, verbose_name='نوع رویداد'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='مرورگر کاربر'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='config',
            field=models.JSONField(default=dict, verbose_name='پیکربندی'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='height',
            field=models.PositiveIntegerField(default=3, verbose_name='ارتفاع'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='position_x',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت X'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='position_y',
            field=models.PositiveIntegerField(default=0, verbose_name='موقعیت Y'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='widget_type',
            field=models.CharField(choices=[('chart', 'Chart'), ('metric', 'Metric'), ('table', 'Table'), ('list', 'List')], max_length=20, verbose_name='نوع ویجت'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='width',
            field=models.PositiveIntegerField(default=4, verbose_name='عرض'),
        ),
        migrations.AlterField(
            model_name='report',
            name='data',
            field=models.JSONField(default=dict, verbose_name='داده\u200cهای گزارش'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='report',
            name='filters',
            field=models.JSONField(default=dict, verbose_name='فیلترهای اعمال شده'),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='report',
            name='period_end',
            field=models.DateField(verbose_name='پایان دوره'),
        ),
        migrations.AlterField(
            model_name='report',
            name='period_start',
            field=models.DateField(verbose_name='شروع دوره'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('financial', 'Financial Report'), ('user_analytics', 'User Analytics'), ('course_analytics', 'Course Analytics'), ('test_analytics', 'Test Analytics'), ('session_analytics', 'Session Analytics'), ('sales', 'Sales Report')], max_length=30, verbose_name='نوع گزارش'),
        ),
    ]
