# Generated by Django 4.2.24 on 2025-11-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_activity_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('code', models.CharField(max_length=10, verbose_name='کد تایید')),
                ('purpose', models.CharField(choices=[('signup', 'ثبت\u200cنام'), ('login', 'ورود'), ('password_reset', 'بازیابی رمز عبور')], default='signup', max_length=20, verbose_name='هدف')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
            ],
            options={
                'verbose_name': 'کد تایید',
                'verbose_name_plural': 'کدهای تایید',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'code', 'is_verified'], name='dashboard_o_phone_n_e590db_idx'), models.Index(fields=['phone_number', 'purpose'], name='dashboard_o_phone_n_a22400_idx')],
            },
        ),
    ]
