# Generated by Django 4.2.24 on 2025-12-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_add_latin_name_fields_and_update_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID from SMS provider', max_length=50, null=True, verbose_name='شناسه تراکنش'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد تایید'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['phone_number', 'transaction_id'], name='dashboard_o_phone_n_8f17e7_idx'),
        ),
    ]
