# Generated by Django 4.2.24 on 2026-05-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_add_transaction_id_to_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of verification attempts'),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='code_hash',
            field=models.CharField(default='!', help_text='Hashed OTP code (PBKDF2)', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otpcode',
            name='provider_error',
            field=models.CharField(blank=True, help_text='Provider error code', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='provider_status',
            field=models.CharField(blank=True, help_text='SMS delivery status', max_length=32, null=True),
        ),
    ]
